version: '3'
services:
  autoagents:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: linksoul.ai/autoagents:1.0
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_KEY=${SERPAPI_KEY}
    networks:
      - bridge  # Add the network here

networks:
  bridge:
    external: true
